# Generated by Django 6.0.7 on 2026-10-04 20:52

from django.db import migrations, models

import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caretakerinvite',
            name='token',
            field=models.CharField(default=members.models.generate_invite_token, max_length=64, unique=True),
        ),
    ]
