# Generated by Django 6.0.7 on 2026-10-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_alter_caretakerinvite_token"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CaretakerInvite",
            new_name="UserInvite",
        ),
        migrations.AddField(
            model_name="userinvite",
            name="role",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("caretaker", "Caretaker"),
                    ("careseeker", "Careseeker"),
                ],
                default="caretaker",
            ),
        ),
    ]